var user = 
{
"login": "ssettle3",
"id": 10368381,
"avatar_url": "https://avatars.githubusercontent.com/u/10368381?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/ssettle3",
"html_url": "https://github.com/ssettle3",
"followers_url": "https://api.github.com/users/ssettle3/followers",
"following_url": "https://api.github.com/users/ssettle3/following{/other_user}",
"gists_url": "https://api.github.com/users/ssettle3/gists{/gist_id}",
"starred_url": "https://api.github.com/users/ssettle3/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/ssettle3/subscriptions",
"organizations_url": "https://api.github.com/users/ssettle3/orgs",
"repos_url": "https://api.github.com/users/ssettle3/repos",
"events_url": "https://api.github.com/users/ssettle3/events{/privacy}",
"received_events_url": "https://api.github.com/users/ssettle3/received_events",
"type": "User",
"site_admin": false,
"name": "Stephen Settle",
"company": "",
"blog": "",
"location": "Atlanta, GA",
"email": "ssettle3@gmail.com",
"hireable": false,
"bio": null,
"public_repos": 13,
"public_gists": 0,
"followers": 1,
"following": 7,
"created_at": "2015-01-02T03:07:35Z",
"updated_at": "2015-01-26T18:17:24Z"
}